# Generated by Django 6.0.2 on 2026-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стрижки')),
                ('price', models.IntegerField(verbose_name='Цена (руб)')),
                ('duration_min', models.IntegerField(default=60, verbose_name='Длительность (мин)')),
                ('difficulty', models.IntegerField(choices=[(1, '⭐ Легко'), (2, '⭐⭐ Средне'), (3, '⭐⭐⭐ Сложно'), (4, '⭐⭐⭐⭐ Эксперт')], default=2, verbose_name='Сложность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
