# Generated by Django 6.0.2 on 2026-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '⭐ Легко'), (2, '⭐⭐ Середньо'), (3, '⭐⭐⭐ Важко'), (4, '⭐⭐⭐⭐ Експерт')], default=2, verbose_name='Складність'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_min',
            field=models.IntegerField(default=60, verbose_name='Тривалість (хв)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Ціна (грн)'),
        ),
    ]
