# Generated by Django 6.0.2 on 2026-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_barber_appointment_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(blank=True, verbose_name='Характеристика / Досвід'),
        ),
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Фото майстра'),
        ),
    ]
