# Generated by Django 6.0.2 on 2026-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_barber_description_barber_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг (наприклад, 4.8)'),
        ),
        migrations.AddField(
            model_name='barber',
            name='reviews',
            field=models.TextField(blank=True, verbose_name='Відгуки клієнтів'),
        ),
    ]
