# Generated by Django 6.0.2 on 2026-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_barber_rating_barber_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Очікує підтвердження'), ('confirmed', '✅ Підтверджено'), ('rejected', '❌ Відхилено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
