# Generated by Django 6.0.2 on 2026-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_appointment_status_alter_barber_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='🔥 Акційна пропозиція'),
        ),
    ]
