# Generated by Django 6.0.4 on 2026-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_is_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('text', models.TextField(verbose_name='Відгук')),
                ('rating', models.IntegerField(default=5, verbose_name='Оцінка (1-5)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Опублікувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
