# Generated by Django 6.0.4 on 2026-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис компанії')),
            ],
            options={
                'verbose_name': 'Про нас (Опис)',
                'verbose_name_plural': 'Про нас (Опис)',
            },
        ),
        migrations.CreateModel(
            name='BarberRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вимога')),
            ],
            options={
                'verbose_name': 'Вимога для барбера',
                'verbose_name_plural': 'Вимоги для барбера',
            },
        ),
    ]
