# Generated by Django 6.0.4 on 2026-04-14 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_aboutcompany_barberrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='reviews',
            field=models.TextField(blank=True, verbose_name='Відгуки клієнтів (цитати)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка (1-5)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото'),
        ),
    ]
