# Generated by Django 6.0.4 on 2026-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_barber_reviews_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Діє до (Дата і час)'),
        ),
    ]
