# Generated by Django 6.0.4 on 2026-04-20 17:27

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_promo_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[services.models.validate_future_date], verbose_name='Діє до (Дата і час)'),
        ),
    ]
