# Generated by Django 6.0.4 on 2026-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_promo_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стара ціна (до акції)'),
        ),
    ]
