# Generated by Django 6.0.4 on 2026-04-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='reviews',
            new_name='reviews_text',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.barber', verbose_name='Кого оцінюєте? (Майстер)'),
        ),
    ]
