# Generated by Django 6.0.4 on 2026-05-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_rename_reviews_barber_reviews_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії (Альбому)')),
                ('cover_image', models.ImageField(upload_to='gallery/covers/', verbose_name='Обкладинка альбому')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія галереї',
                'verbose_name_plural': 'Категорії галереї',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Фотографія')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.gallerycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Фотографія галереї',
                'verbose_name_plural': 'Фотографії галереї',
            },
        ),
    ]
